export const t = {
  appName: 'Scorekeeper',
  subtitle: 'Hartenjagen & klaverjassen',
  newGame: 'Nieuw spel',
  newGameSamePlayers: 'Nieuw spel, zelfde spelers',
  inProgress: 'Bezig',
  finished: 'Afgelopen',
  noGames: 'Nog geen spellen. Begin een nieuw spel!',
  players: 'Spelers',
  playerName: (i: number) => `Speler ${i + 1}`,
  addPlayer: '+ Speler toevoegen',
  removePlayer: 'Verwijderen',
  rules: 'Spelregels',
  paymentPerPoint: 'Cent per punt',
  paymentGameFee: 'Cent per spel',
  turnAt: 'Retour vanaf',
  start: 'Starten',
  back: 'Terug',
  round: 'Ronde',
  enterRound: 'Ronde invoeren',
  remaining: (left: number, total: number) => `Nog ${left} van ${total} punten`,
  tooMany: (over: number) => `${over} punten te veel!`,
  save: 'Opslaan',
  cancel: 'Annuleren',
  pit: 'Pit!',
  pitTitle: (name: string) => `${name} haalt alles!`,
  pitSelf: (delta: number) => `${delta} voor de speler`,
  pitOthers: (delta: number) => `+${delta} voor de rest`,
  undoRound: 'Laatste ronde ongedaan maken',
  deleteGame: 'Spel verwijderen',
  deleteConfirm: 'Dit spel verwijderen?',
  winner: (name: string) => `${name} wint!`,
  payments: 'Afrekening',
  pays: (from: string, amount: string, to: string) => `${from} betaalt ${amount} aan ${to}`,
  paymentsNote: 'Exclusief verrekening van eventuele pit-potjes.',
  receivesTotal: (name: string, amount: string) => `${name} ontvangt ${amount}`,
  returnPhase: 'retour',
  returnBanner: 'Retourspel — punten tellen af',
  lowest: 'laagste',
  highest: 'hoogste',
  tieTitle: 'Meerdere spelers onder de 0!',
  tieQuestion: 'Wie heeft zich als eerste uitgemeld?',
  total: 'Totaal',
  // Klaverjassen
  gameTypeLabel: 'Spel',
  hartenjagen: 'Hartenjagen',
  klaverjassen: 'Klaverjassen',
  teams: 'Teams',
  teamWij: 'Wij',
  teamZij: 'Zij',
  variantLabel: 'Telling',
  firstDealer: 'Wie deelt eerst?',
  deals: (name: string) => `${name} deelt`,
  potje: 'Potje',
  enterPotje: 'Potje invoeren',
  trumpQuestion: 'Wie maakte troef?',
  roem: 'Roem',
  resetRoem: 'wissen',
  points: 'Punten',
  klaverjasRemaining: (left: number) => (left === 0 ? 'Samen 162 ✓' : left > 0 ? `Nog ${left} tot 162` : `${-left} te veel!`),
  nat: 'nat',
  natWarning: (trump: string, other: string) => `${trump} gaat nat — alle punten en roem naar ${other}`,
  pitWarning: (name: string, bonus: number) => `Pit voor ${name}: alle punten + ${bonus}`,
  leading: 'aan kop',
  teamWins: (name: string) => {
    const lower = name.trim().toLowerCase()
    return lower === 'wij' || lower === 'zij' ? `${name.trim()} winnen!` : `${name} wint!`
  },
}
