export const t = {
  appName: 'Scorekeeper',
  subtitle: 'Hartenjagen',
  newGame: 'Nieuw spel',
  newGameSamePlayers: 'Nieuw spel, zelfde spelers',
  inProgress: 'Bezig',
  finished: 'Afgelopen',
  noGames: 'Nog geen spellen. Begin een nieuw spel!',
  players: 'Spelers',
  playerName: (i: number) => `Speler ${i + 1}`,
  addPlayer: '+ Speler toevoegen',
  removePlayer: 'Verwijderen',
  rules: 'Spelregels',
  paymentPerPoint: 'Cent per punt',
  paymentGameFee: 'Cent per spel',
  turnAt: 'Retour vanaf',
  start: 'Starten',
  back: 'Terug',
  round: 'Ronde',
  enterRound: 'Ronde invoeren',
  remaining: (left: number, total: number) => `Nog ${left} van ${total} punten`,
  tooMany: (over: number) => `${over} punten te veel!`,
  save: 'Opslaan',
  cancel: 'Annuleren',
  pit: 'Pit!',
  pitTitle: (name: string) => `${name} haalt alles!`,
  pitSelf: (delta: number) => `${delta} voor de speler`,
  pitOthers: (delta: number) => `+${delta} voor de rest`,
  undoRound: 'Laatste ronde ongedaan maken',
  deleteGame: 'Spel verwijderen',
  deleteConfirm: 'Dit spel verwijderen?',
  winner: (name: string) => `${name} wint!`,
  payments: 'Afrekening',
  pays: (from: string, amount: string, to: string) => `${from} betaalt ${amount} aan ${to}`,
  receivesTotal: (name: string, amount: string) => `${name} ontvangt ${amount}`,
  returnPhase: 'retour',
  returnBanner: 'Retourspel — punten tellen af',
  lowest: 'laagste',
  tieTitle: 'Meerdere spelers onder de 0!',
  tieQuestion: 'Wie heeft zich als eerste uitgemeld?',
  total: 'Totaal',
}
